### ISSUE TITLE
Upgrade to latest version of OpenAPITools/openapi-style-validator

### ISSUE THREAD

**Issue by gervaisb** [jrouly/sbt-openapi-style-validator#9]
There are some pending changes on the [/OpenAPITools/openapi-style-validator](https://github.com/OpenAPITools/openapi-style-validator). 

Especially this discussion that is blocking us: https://github.com/OpenAPITools/openapi-style-validator/issues/152

Would you mind upgrading the library once the related pull request will be accepted ?

**Comment by gervaisb** [comment]
Awesome. Thank you.

Do you plan to release it soon ?

**Comment by jrouly** [comment]
Sorry about that, just released [v0.0.5](https://github.com/jrouly/sbt-openapi-style-validator/releases/tag/v0.0.5).
